ALTER TABLE tasks
DROP
CONSTRAINT fk_assigned_to;

ALTER TABLE tasks
DROP
CONSTRAINT fk_created_by;

CREATE TABLE task
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title          VARCHAR(255)                            NOT NULL,
    description    VARCHAR(255)                            NOT NULL,
    status         VARCHAR(255)                            NOT NULL,
    priority       VARCHAR(255)                            NOT NULL,
    deadline       date                                    NOT NULL,
    created_at     date                                    NOT NULL,
    assigned_to_id BIGINT                                  NOT NULL,
    created_by_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_ASSIGNED_TO FOREIGN KEY (assigned_to_id) REFERENCES "user" (id);

ALTER TABLE task
    ADD CONSTRAINT FK_TASK_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES "user" (id);

DROP TABLE tasks CASCADE;

DROP TABLE users CASCADE;